### ISSUE TITLE
能说一下开发环境嘛？jdk版本……tools版本这些

### ISSUE THREAD

**Issue by peiqizzq** [aa112901/remusic#109]
开发的时候环境不对就会有好多东西跟截图展现的不一样

**Comment by peiqizzq** [comment]
说错了 我还以为第三个人脉那个图标不能用是版本原因呢 原来就是不能用的。
不过现在连不上了，全都是在加载中

**Comment by gs666** [comment]
#99

**Comment by peiqizzq** [comment]
> #99

文档里的APK安装包安装了之后也是这样的情况，也是因为那个代码的原因嘛？
