### ISSUE TITLE
播放状态显示不正确

### ISSUE THREAD

**Issue by guoxj** [aa112901/remusic#17]
一.本地音乐里面，单曲列表。
步骤：1.点击第一首歌，显示播放，✔️
2.点击第二首歌，显示播放，✔️
3.再次点击第一首歌，就乱了。❌
二。最近播放列表
同样的问题。有点乱

**Comment by aa112901** [comment]
你的乱是什么意思，我这里按照你的步骤播放都是正常的

**Comment by guoxj** [comment]
比如说列表里面有5首歌曲。你从第一首点击到第五首。然后播放图标显示的就错乱啦。你试试看

**Comment by guoxj** [comment]
额。。要是你再现不了的话能否留个联系方式。我加下你。

**Comment by aa112901** [comment]
重现不了，是要快速点击？

**Comment by guoxj** [comment]
不必快速点击。 点击歌曲。ABCDABCDCD这样子。随便多点击几次就出现了

**Comment by guoxj** [comment]
[IMG_0221.iphone5.mp4.zip](https://github.com/aa112901/remusic/files/588592/IMG_0221.iphone5.mp4.zip)
我录下来了。你看下

**Comment by guoxj** [comment]
问题已经解决。在MusicFragment.java下面的ListItemViewHolder类下面的onClick方法。
修改为
 final Handler handler = new Handler();
                handler.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        long[] list = new long[mList.size()];
                        HashMap<Long, MusicInfo> infos = new HashMap();
                        for (int i = 0; i < mList.size(); i++) {
                            list[i] = mList.get(i).songId;
                            MusicInfo info = mList.get(i);
                            info.albumData = MusicUtils.getAlbumArtUri(info.albumId) + "";
                            infos.put(list[i], mList.get(i));
                        }
                        MusicPlayer.playAll(infos, list, getAdapterPosition() - 1, false);
                        Handler handler1 = new Handler();
                        handler1.postDelayed(new Runnable() {
                            @Override
                            public void run() {
                                notifyItemChanged(currentlyPlayingPosition);
                                notifyItemChanged(getAdapterPosition());
                            }
                        }, 50);
                    }
                }, 100);

**Comment by guoxj** [comment]
谢谢作者的无私奉献！
