### ISSUE TITLE
播放音乐代码断点调试跟踪不到音频源地址？求指教。

### ISSUE THREAD

**Issue by yorke1314** [aa112901/remusic#51]
在MusicPlayer.playAll();后断点跟代码到
mService.open(infos, list, forceShuffle ? -1 : position);
mService.play();

实际的播放音乐代码该跳到哪里？在下小白，望不吝赐教。
不知道是不是在MediaService里面？我尝试在MediaService的方法里面加断点，都没进入

**Comment by yorke1314** [comment]
mService.play();的时候应该还不知道音频资源的地址吧，不知道是在什么时候获取具体的音频资源地址？

**Comment by aa112901** [comment]
MediaService 是主要的播放类，activity通过aidl 与MediaService通信，activity只提供id给mediaservice，具体地址由MediaService自己获取

**Comment by yorke1314** [comment]
@aa112901 谢谢大神，明白了，多谢赐教
