### ISSUE TITLE
修改后没数据

### ISSUE THREAD

**Issue by Mrfanwei** [aa112901/remusic#59]
我将原来的注释掉          
 /*Request request = new Request.Builder()
                    .url(url)
                    .header("RANGE", "bytes=" + completedSize + "-")//  Http value set breakpoints RANGE
                    .addHeader("Referer", url)
                    .build();*/

然后按照下面两种方法修改都没数据，跪求解：
第一种修改
Request request = new Request.Builder()
                    .url(url)
                    .header("RANGE", "bytes=" + completedSize + "-")//  Http value set breakpoints RANGE
                    .addHeader("Referer", url)
                   .addHeader("user-agent", "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:0.9.4)")
                    .build();

第二种修改：
              Request request = new Request.Builder()
                      .addHeader("user-agent", "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:0.9.4)")
                    .url(url)
                    .build();

**Comment by ALx8023** [comment]
![image](https://user-images.githubusercontent.com/16871633/29446731-579de7ea-8420-11e7-98b0-2a792f0e573e.png)
