### ISSUE TITLE
请问如何实现双行歌词，中英双语同时选中和显示

### ISSUE THREAD

**Issue by zjmok** [aa112901/remusic#78]

**Comment by zjmok** [comment]
srt转换为lrc，双行规则是同一个时间点，勉强实现的方案是修改onDraw里面的判断
`if (i == mCurRow
                    || (i == mCurRow - 1 && mLrcRows.get(i).getTime() == mLrcRows.get(mCurRow).getTime())
                    ) {//画高亮歌词
`
此时mCurRow是同一时间点的后一条lrc，
bug来了，水平滚动效果没有了，不知道怎么修复水平滚动

**Comment by zhangliangming** [comment]
如果是要实现音译和翻译的双行滚动歌词，你可以到我这个播放器看看：https://github.com/zhangliangming/HappyPlayer5.git
哈哈，我是来这里吸粉的。

**Comment by zhangliangming** [comment]
@the-mok https://github.com/zhangliangming/HappyPlayer5.git

**Comment by zjmok** [comment]
@zhangliangming 非常感谢
